version: '3.7'

services:

  web_dev:
    build:
      context: .
      target: build_env
    tty: true
    ports:
      - "4200:4200"
    volumes:
      - .:/root/my-app
    environment:
      TZ: Asia/Tokyo
